services:
  postgres:
    image: postgres:16-alpine
    container_name: erp_crm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: erp_crm
      POSTGRES_PASSWORD: erp_crm
      POSTGRES_DB: erp_crm
    ports:
      - '5432:5432'
    volumes:
      - erp_crm_postgres_data:/var/lib/postgresql/data

volumes:
  erp_crm_postgres_data:
